spring:
  application:
    name: producer  # 注册到服务中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: producer    #服务名
        prefer-ip-address: true   #使用ip注册
---
server:
  port: 9002 # consul客户端端口号
spring:
  profiles: server1
---
server:
  port: 9004 # consul客户端端口号
spring:
  profiles: server2