server:
  port: 9003
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true # 使用ip注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}