server:
  port: 9003
spring:
  application:
    name: consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consumer
        prefer-ip-address: true